apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: customer
spec:
  description: ArgoCD project for apps
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
