apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuer.selfsigned.yaml
  - namespace.yaml

helmCharts:
  - repo: https://charts.jetstack.io
    name: cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    version: 1.12.10
    valuesFile: values.yaml
  