apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - repo: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    releaseName: ingress-nginx
    namespace: ingress-nginx
    version: 4.10.1
    valuesFile: values.yaml
  